version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: orient base dir
          command: pwd
      - run:
          name: identify repo objects 
          command: ls
      - add_ssh_keys:
          fingerprints:
            - "8b:10:7c:49:05:c3:a0:95:ba:7b:38:29:bc:47:6f:7d"
      - run: echo "deb  http://deb.debian.org/debian  stretch main" >> /etc/apt/sources.list
      - run: echo "deb-src  http://deb.debian.org/debian  stretch main" >> /etc/apt/sources.list
      - run: cat /etc/apt/sources.list
      - run: apt update
      - run:
          name: Install SCP 
          command: apt -y install openssh-client 
      - run:
          name: Install AWS CLI tools
          command: |
            apt-get update
            apt-get install -y python-pip python-dev
            pip install awscli
            aws --version

      - run:
          name: Place installer on Core EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -o StrictHostKeyChecking=no -r /root/project/saas-light-11-8-s3-comply-installer.tar.gz circleci@comply-circleci-poc-core.dequelabs.com:/home/circleci

      - run:
          name: Install AWS tools on Core EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -o StrictHostKeyChecking=no -r /root/project/ci-scripts/install.aws.tools.sh circleci@comply-circleci-poc-core.dequelabs.com:/home/circleci
            ssh -o StrictHostKeyChecking=no circleci@comply-circleci-poc-core.dequelabs.com 'sudo bash -s' < install.aws.tools.sh 

      - run:
          name: Install comply core prereqs on EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -o StrictHostKeyChecking=no -r /root/project/ci-scripts/prereq-setup.sh circleci@comply-circleci-poc-core.dequelabs.com:/home/circleci
            ssh -o StrictHostKeyChecking=no circleci@comply-circleci-poc-core.dequelabs.com 'sudo bash -s' < prereq-setup.sh core

      - run:
          name: Install comply core on EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -o StrictHostKeyChecking=no -r /root/project/ci-scripts/install-comply.sh circleci@comply-circleci-poc-core.dequelabs.com:/home/circleci
            ssh -o StrictHostKeyChecking=no circleci@comply-circleci-poc-core.dequelabs.com 'sudo bash -s' < install-comply.sh core

      - run:
          name: Run comply core start order on EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -o StrictHostKeyChecking=no -r /root/project/ci-scripts/start_order.sh circleci@comply-circleci-poc-core.dequelabs.com:/home/circleci
            ssh -o StrictHostKeyChecking=no circleci@comply-circleci-poc-core.dequelabs.com 'sudo bash -s' < start_order.sh core

      - run:
          name: Place installer on Analysis EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -o StrictHostKeyChecking=no -r /root/project/saas-light-11-8-s3-comply-installer.tar.gz circleci@comply-circleci-poc-analysis.dequelabs.com:/home/circleci

      - run:
          name: Install AWS tools on Analysis EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -o StrictHostKeyChecking=no -r /root/project/ci-scripts/install.aws.tools.sh circleci@comply-circleci-poc-analysis.dequelabs.com:/home/circleci
            ssh -o StrictHostKeyChecking=no circleci@comply-circleci-poc-analysis.dequelabs.com 'sudo bash -s' < install.aws.tools.sh

      - run:
          name: Install comply Analysis prereqs on EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -o StrictHostKeyChecking=no -r /root/project/ci-scripts/prereq-setup.sh circleci@comply-circleci-poc-analysis.dequelabs.com:/home/circleci
            ssh -o StrictHostKeyChecking=no circleci@comply-circleci-poc-analysis.dequelabs.com 'sudo bash -s' < prereq-setup.sh analysis

      - run:
          name: Install comply Analysis on EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -o StrictHostKeyChecking=no -r /root/project/ci-scripts/install-comply.sh circleci@comply-circleci-poc-analysis.dequelabs.com:/home/circleci
            ssh -o StrictHostKeyChecking=no circleci@comply-circleci-poc-analysis.dequelabs.com 'sudo bash -s' < install-comply.sh analysis

      - run:
          name: Run comply analysis start order on EC2
          command: |
            chmod 600 ~/.ssh/id_*
            scp -o StrictHostKeyChecking=no -r /root/project/ci-scripts/start_order.sh circleci@comply-circleci-poc-analysis.dequelabs.com:/home/circleci
            ssh -o StrictHostKeyChecking=no circleci@comply-circleci-poc-analysis.dequelabs.com 'sudo bash -s' < start_order.sh analysis

  deploy:
    machine:
        enabled: true
    steps:
      - run:
          name: Execute SCP to EC2
          command: |
            chmod 600 ~/.ssh/id_*
      
